function [Global_DA,Global_A1,Global_JA,Global_DBC,Global_M,Boundarya,Boundaryb,Boundaryc,Boundaryd] = finematrix_DBC(a,rho,nx,ny,Nx,Ny,partition_unity)


hx = 1/Nx/nx;
hy = 1/Ny/ny;
ratiox = Nx*nx/Ny/ny;
ratioy = Ny*ny/Nx/nx;
% ratioy = ratiox;
idx = reshape(1:(Ny*ny+1)*(Nx*nx+1),Ny*ny+1,Nx*nx+1);
idx1 = idx(1:end-1,1:end-1);
idx2 = idx1 + Ny*ny+1;
idx3 = idx1 + 1;
idx4 = idx1 + 1 + Ny*ny+1;
loc_M_idx3 = [idx1(:);idx2(:);idx3(:);idx4(:)];
loc_DAx   = sparse(loc_M_idx3, [1:Ny*Nx*ny*nx,1:Ny*Nx*ny*nx,1:Ny*Nx*ny*nx,1:Ny*Nx*ny*nx] ,...
            kron([-1;-1;1;1], ones(Ny*Nx*ny*nx,1) ) );
loc_DAy   = sparse(loc_M_idx3, [1:Ny*Nx*ny*nx,1:Ny*Nx*ny*nx,1:Ny*Nx*ny*nx,1:Ny*Nx*ny*nx] ,...
            kron([-1;1;-1;1], ones(Ny*Nx*ny*nx,1) ) );
dpartition = sum((loc_DAx'*partition_unity).^2,2)*ratiox^2 +sum((loc_DAy'*partition_unity).^2,2)*ratioy^2 ;


idx = reshape(1:Ny*(ny+1)*Nx*(nx+1),Ny*(ny+1),Nx*(nx+1));

% %           boundary1
% %           ---------
% %          |         |
% %          |         |
% % boundary3|         |boundary4
% %          |         |
% %          |         |
% %           ---------
% %           boundary2

boundary1 = idx(1:ny+1:Ny*(ny+1),:);
boundary2 = idx(ny+1:ny+1:Ny*(ny+1),:);
boundary3 = idx(:,1:nx+1:Nx*(nx+1));
boundary4 = idx(:,nx+1:nx+1:Nx*(nx+1));

% %[idx1, idx2;
% % idx3, idx4]

idx1 = idx;
idx1([boundary2(:);boundary4(:)]) =[];
idx2 = idx1 + Ny*(ny+1);
idx3 = idx1 + 1;
idx4 = idx1 + 1 + Ny*(ny+1);


Global_DA = sparse([idx1(:);idx2(:);idx3(:);idx4(:);  idx1(:);idx2(:);idx3(:);idx4(:);  idx1(:);idx2(:);idx3(:);idx4(:);  idx1(:);idx2(:);idx3(:);idx4(:)],...
                   [idx1(:);idx1(:);idx1(:);idx1(:);  idx2(:);idx2(:);idx2(:);idx2(:);  idx3(:);idx3(:);idx3(:);idx3(:);  idx4(:);idx4(:);idx4(:);idx4(:)],...
                   kron([2;-2;1;-1; -2;2;-1;1; 1;-1;2;-2; -1;1;-2;2]*ratiox+[2;1;-2;-1; 1;2;-1;-2; -2;-1;2;1; -1;-2;1;2]*ratioy, a(:) )/6 );

               
Boundarya = boundary1;
Boundaryb = boundary2;
Boundaryc = boundary3;
Boundaryd = boundary4;
Boundarya( 1 , : ) = [];
Boundaryb(end, : ) = [];
Boundaryc( : , 1 ) = [];
Boundaryd( : ,end) = [];

boundary1(:,nx+1:nx+1:Nx*(nx+1)) = [];
boundary2(:,nx+1:nx+1:Nx*(nx+1)) = [];
boundary3(ny+1:ny+1:Ny*(ny+1),:) = [];
boundary4(ny+1:ny+1:Ny*(ny+1),:) = [];

Boundary1 = boundary1( 1 , : );
Boundary2 = boundary2(end, : );
Boundary3 = boundary3( : , 1 );
Boundary4 = boundary4( : ,end);

boundary1( 1 , : ) = [];
boundary2(end, : ) = [];
boundary3( : , 1 ) = [];
boundary4( : ,end) = [];
ax1 = a( 1:ny:Ny*ny,:);
ax2 = a(ny:ny:Ny*ny,:);
ax3 = a(:, 1:nx:Nx*nx,:);
ax4 = a(:,nx:nx:Nx*nx,:);

ba1 = (ax1( 1 ,:));
ba2 = (ax2(end,:));
ba3 = (ax3(:, 1 ));
ba4 = (ax4(:,end));

ax1 = ax1(2:end,:);
ax2 = ax2(1:end-1,:);
ax3 = ax3(:,2:end);
ax4 = ax4(:,1:end-1);

dof_y = (ny+1)*Ny;
Global_A1 = sparse([boundary1(:);boundary1(:)+1;boundary1(:)+dof_y;boundary1(:)+dof_y+1;  boundary2(:);boundary2(:)-1;boundary2(:)+dof_y;boundary2(:)+dof_y-1;...
                    boundary1(:);boundary1(:)+1;boundary1(:)+dof_y;boundary1(:)+dof_y+1;  boundary2(:);boundary2(:)-1;boundary2(:)+dof_y;boundary2(:)+dof_y-1;...
                    boundary1(:);boundary1(:)+1;boundary1(:)+dof_y;boundary1(:)+dof_y+1;  boundary2(:);boundary2(:)-1;boundary2(:)+dof_y;boundary2(:)+dof_y-1;...
                    boundary1(:);boundary1(:)+1;boundary1(:)+dof_y;boundary1(:)+dof_y+1;  boundary2(:);boundary2(:)-1;boundary2(:)+dof_y;boundary2(:)+dof_y-1],...
                   [boundary1(:);boundary1(:);boundary1(:);boundary1(:);  boundary1(:);boundary1(:);boundary1(:);boundary1(:);...
                    boundary1(:)+dof_y;boundary1(:)+dof_y;boundary1(:)+dof_y;boundary1(:)+dof_y;  boundary1(:)+dof_y;boundary1(:)+dof_y;boundary1(:)+dof_y;boundary1(:)+dof_y;...
                    boundary2(:);boundary2(:);boundary2(:);boundary2(:);  boundary2(:);boundary2(:);boundary2(:);boundary2(:);...
                    boundary2(:)+dof_y;boundary2(:)+dof_y;boundary2(:)+dof_y;boundary2(:)+dof_y;  boundary2(:)+dof_y;boundary2(:)+dof_y;boundary2(:)+dof_y;boundary2(:)+dof_y],...
                    [ax1(:)/6;-ax1(:)/6;ax1(:)/12;-ax1(:)/12;-ax2(:)/6;ax2(:)/6;-ax2(:)/12;ax2(:)/12;...
                     ax1(:)/12;-ax1(:)/12;ax1(:)/6;-ax1(:)/6;-ax2(:)/12;ax2(:)/12;-ax2(:)/6;ax2(:)/6;...
                     -ax1(:)/6;ax1(:)/6;-ax1(:)/12;ax1(:)/12;ax2(:)/6;-ax2(:)/6;ax2(:)/12;-ax2(:)/12;...
                     -ax1(:)/12;ax1(:)/12;-ax1(:)/6;ax1(:)/6;ax2(:)/12;-ax2(:)/12;ax2(:)/6;-ax2(:)/6]*ratioy,Ny*(ny+1)*Nx*(nx+1),Ny*(ny+1)*Nx*(nx+1));
                 
Global_A2 = sparse([boundary3(:);boundary3(:)+dof_y;boundary3(:)+1;boundary3(:)+dof_y+1;  boundary4(:);boundary4(:)-dof_y;boundary4(:)+1;boundary4(:)+1-dof_y;...
                    boundary3(:);boundary3(:)+dof_y;boundary3(:)+1;boundary3(:)+dof_y+1;  boundary4(:);boundary4(:)-dof_y;boundary4(:)+1;boundary4(:)+1-dof_y;...
                    boundary3(:);boundary3(:)+dof_y;boundary3(:)+1;boundary3(:)+dof_y+1;  boundary4(:);boundary4(:)-dof_y;boundary4(:)+1;boundary4(:)+1-dof_y;...
                    boundary3(:);boundary3(:)+dof_y;boundary3(:)+1;boundary3(:)+dof_y+1;  boundary4(:);boundary4(:)-dof_y;boundary4(:)+1;boundary4(:)+1-dof_y],...
                   [boundary3(:);boundary3(:);boundary3(:);boundary3(:);  boundary3(:);boundary3(:);boundary3(:);boundary3(:);...
                    boundary3(:)+1;boundary3(:)+1;boundary3(:)+1;boundary3(:)+1;  boundary3(:)+1;boundary3(:)+1;boundary3(:)+1;boundary3(:)+1;...
                    boundary4(:);boundary4(:);boundary4(:);boundary4(:);  boundary4(:);boundary4(:);boundary4(:);boundary4(:);...
                    boundary4(:)+1;boundary4(:)+1;boundary4(:)+1;boundary4(:)+1;  boundary4(:)+1;boundary4(:)+1;boundary4(:)+1;boundary4(:)+1],...
                    [ax3(:)/6;-ax3(:)/6;ax3(:)/12;-ax3(:)/12;-ax4(:)/6;ax4(:)/6;-ax4(:)/12;ax4(:)/12;...
                     ax3(:)/12;-ax3(:)/12;ax3(:)/6;-ax3(:)/6;-ax4(:)/12;ax4(:)/12;-ax4(:)/6;ax4(:)/6;...
                     -ax3(:)/6;ax3(:)/6;-ax3(:)/12;ax3(:)/12;ax4(:)/6;-ax4(:)/6;ax4(:)/12;-ax4(:)/12;...
                     -ax3(:)/12;ax3(:)/12;-ax3(:)/6;ax3(:)/6;ax4(:)/12;-ax4(:)/12;ax4(:)/6;-ax4(:)/6]*ratiox,Ny*(ny+1)*Nx*(nx+1),Ny*(ny+1)*Nx*(nx+1));

Global_JA1 = sparse([boundary1(:);boundary1(:)+dof_y;  boundary2(:);boundary2(:)+dof_y;...
                     boundary1(:);boundary1(:)+dof_y;  boundary2(:);boundary2(:)+dof_y;...
                     boundary1(:);boundary1(:)+dof_y;  boundary2(:);boundary2(:)+dof_y;...
                     boundary1(:);boundary1(:)+dof_y;  boundary2(:);boundary2(:)+dof_y],...
                   [boundary1(:);boundary1(:);boundary1(:);boundary1(:);...
                    boundary1(:)+dof_y;boundary1(:)+dof_y;boundary1(:)+dof_y;boundary1(:)+dof_y;...
                    boundary2(:);boundary2(:);boundary2(:);boundary2(:);...
                    boundary2(:)+dof_y;boundary2(:)+dof_y;boundary2(:)+dof_y;boundary2(:)+dof_y],...
                    [(ax1(:)+ax2(:))/6;(ax1(:)+ax2(:))/12; -(ax1(:)+ax2(:))/6;-(ax1(:)+ax2(:))/12;...
                     (ax1(:)+ax2(:))/12;(ax1(:)+ax2(:))/6; -(ax1(:)+ax2(:))/12;-(ax1(:)+ax2(:))/6;...
                     -(ax1(:)+ax2(:))/6;-(ax1(:)+ax2(:))/12; (ax1(:)+ax2(:))/6;(ax1(:)+ax2(:))/12;...
                     -(ax1(:)+ax2(:))/12;-(ax1(:)+ax2(:))/6; (ax1(:)+ax2(:))/12;(ax1(:)+ax2(:))/6],Ny*(ny+1)*Nx*(nx+1),Ny*(ny+1)*Nx*(nx+1));
                 
Global_JA2 = sparse([boundary3(:);boundary3(:)+1;  boundary4(:);boundary4(:)+1;...
                     boundary3(:);boundary3(:)+1;  boundary4(:);boundary4(:)+1;...
                     boundary3(:);boundary3(:)+1;  boundary4(:);boundary4(:)+1;...
                     boundary3(:);boundary3(:)+1;  boundary4(:);boundary4(:)+1],...
                   [boundary3(:);boundary3(:);boundary3(:);boundary3(:);...
                    boundary3(:)+1;boundary3(:)+1;boundary3(:)+1;boundary3(:)+1;...
                    boundary4(:);boundary4(:);boundary4(:);boundary4(:);...
                    boundary4(:)+1;boundary4(:)+1;boundary4(:)+1;boundary4(:)+1],...
                    [(ax3(:)+ax4(:))/6;(ax3(:)+ax4(:))/12; -(ax3(:)+ax4(:))/6;-(ax3(:)+ax4(:))/12;...
                     (ax3(:)+ax4(:))/12;(ax3(:)+ax4(:))/6; -(ax3(:)+ax4(:))/12;-(ax3(:)+ax4(:))/6;...
                     -(ax3(:)+ax4(:))/6;-(ax3(:)+ax4(:))/12; (ax3(:)+ax4(:))/6;(ax3(:)+ax4(:))/12;...
                     -(ax3(:)+ax4(:))/12;-(ax3(:)+ax4(:))/6; (ax3(:)+ax4(:))/12;(ax3(:)+ax4(:))/6],Ny*(ny+1)*Nx*(nx+1),Ny*(ny+1)*Nx*(nx+1));

Global_JA3 = sparse([Boundary1(:);Boundary1(:)+dof_y;  Boundary2(:);Boundary2(:)+dof_y;...
                     Boundary1(:);Boundary1(:)+dof_y;  Boundary2(:);Boundary2(:)+dof_y],...
                   [Boundary1(:);Boundary1(:);Boundary2(:);Boundary2(:);...
                    Boundary1(:)+dof_y;Boundary1(:)+dof_y;Boundary2(:)+dof_y;Boundary2(:)+dof_y],...
                    [ba1(:)/3;ba1(:)/6;  ba2(:)/3;ba2(:)/6;...
                     ba1(:)/6;ba1(:)/3;  ba2(:)/6;ba2(:)/3],Ny*(ny+1)*Nx*(nx+1),Ny*(ny+1)*Nx*(nx+1));

Global_JA4 = sparse([Boundary3(:);Boundary3(:)+1;  Boundary4(:);Boundary4(:)+1;...
                     Boundary3(:);Boundary3(:)+1;  Boundary4(:);Boundary4(:)+1],...
                   [Boundary3(:);Boundary3(:);Boundary4(:);Boundary4(:);...
                    Boundary3(:)+1;Boundary3(:)+1;Boundary4(:)+1;Boundary4(:)+1],...
                    [ba3(:)/3;ba3(:)/6;  ba4(:)/3;ba4(:)/6;...
                     ba3(:)/6;ba3(:)/3;  ba4(:)/6;ba4(:)/3],Ny*(ny+1)*Nx*(nx+1),Ny*(ny+1)*Nx*(nx+1));
                 
Global_JA = Global_JA1+Global_JA2;
Global_DBC = Global_JA3+Global_JA4;
Global_A1 = Global_A1+Global_A2;
                 
Global_M = sparse([idx1(:);idx2(:);idx3(:);idx4(:);  idx1(:);idx2(:);idx3(:);idx4(:);  idx1(:);idx2(:);idx3(:);idx4(:);  idx1(:);idx2(:);idx3(:);idx4(:)],...
                   [idx1(:);idx1(:);idx1(:);idx1(:);  idx2(:);idx2(:);idx2(:);idx2(:);  idx3(:);idx3(:);idx3(:);idx3(:);  idx4(:);idx4(:);idx4(:);idx4(:)],...
                   kron([1/9;1/18;1/18;1/36; 1/18;1/9;1/36;1/18;  1/18;1/36;1/9;1/18;  1/36;1/18;1/18;1/9], rho(:).*dpartition ) );
               
% % Global_M = sparse([idx1(:);idx2(:);idx3(:);idx4(:);  idx1(:);idx2(:);idx3(:);idx4(:);  idx1(:);idx2(:);idx3(:);idx4(:);  idx1(:);idx2(:);idx3(:);idx4(:)],...
% %                    [idx1(:);idx1(:);idx1(:);idx1(:);  idx2(:);idx2(:);idx2(:);idx2(:);  idx3(:);idx3(:);idx3(:);idx3(:);  idx4(:);idx4(:);idx4(:);idx4(:)],...
% %                    kron([1/9;1/18;1/18;1/36; 1/18;1/9;1/36;1/18;  1/18;1/36;1/9;1/18;  1/36;1/18;1/18;1/9], rho(:) )*hx*hy );
               
               